team = ('Oklahoma City Thunder', 'Houston Rockets', 'Los Angeles Lakers', 'Denver Nuggets', 'LA Clippers', 'Minnesota Timberwolves', 'Golden State Warriors', 'Memphis Grizzlies', 'Sacramento Kings', 'Dallas Mavericks')
teamorder = tuple(sorted(team))
print('-=-'*11)
print(f'Top 10 basketball teams in 2025: {team}')
print('-=-'*11)
print(f'Top 5 are: {team[:5]}')
print('-=-'*11)
print(f'The last top 4 are: {team[-4:]}')
print('-=-'*11)
print(f'All the teams in alphabetical order: {teamorder}')
print('-=-'*11)
print(f'The Los Angeles Lakers is in 3th position!')